(cl:in-package vrep_common-srv)
(cl:export '(FUNCTIONNAMEATOBJECTNAME-VAL
          FUNCTIONNAMEATOBJECTNAME
          SCRIPTHANDLEORTYPE-VAL
          SCRIPTHANDLEORTYPE
          INPUTINTS-VAL
          INPUTINTS
          INPUTFLOATS-VAL
          INPUTFLOATS
          INPUTSTRINGS-VAL
          INPUTSTRINGS
          INPUTBUFFER-VAL
          INPUTBUFFER
          RESULT-VAL
          RESULT
          OUTPUTINTS-VAL
          OUTPUTINTS
          OUTPUTFLOATS-VAL
          OUTPUTFLOATS
          OUTPUTSTRINGS-VAL
          OUTPUTSTRINGS
          OUTPUTBUFFER-VAL
          OUTPUTBUFFER
))