// Generated by gencpp from file vrep_common/simRosGetVisionSensorImage.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORIMAGE_H
#define VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORIMAGE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetVisionSensorImageRequest.h>
#include <vrep_common/simRosGetVisionSensorImageResponse.h>


namespace vrep_common
{

struct simRosGetVisionSensorImage
{

typedef simRosGetVisionSensorImageRequest Request;
typedef simRosGetVisionSensorImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetVisionSensorImage
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorImage > {
  static const char* value()
  {
    return "c9fa464de5ffa4b5a019f79bc572d29f";
  }

  static const char* value(const ::vrep_common::simRosGetVisionSensorImage&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetVisionSensorImage > {
  static const char* value()
  {
    return "vrep_common/simRosGetVisionSensorImage";
  }

  static const char* value(const ::vrep_common::simRosGetVisionSensorImage&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorImageRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorImage > 
template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetVisionSensorImageRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetVisionSensorImage > 
template<>
struct DataType< ::vrep_common::simRosGetVisionSensorImageRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorImageResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorImage > 
template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetVisionSensorImageResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetVisionSensorImage > 
template<>
struct DataType< ::vrep_common::simRosGetVisionSensorImageResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORIMAGE_H
