// Generated by gencpp from file vrep_common/simRosSetIntegerParameter.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETINTEGERPARAMETER_H
#define VREP_COMMON_MESSAGE_SIMROSSETINTEGERPARAMETER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetIntegerParameterRequest.h>
#include <vrep_common/simRosSetIntegerParameterResponse.h>


namespace vrep_common
{

struct simRosSetIntegerParameter
{

typedef simRosSetIntegerParameterRequest Request;
typedef simRosSetIntegerParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetIntegerParameter
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetIntegerParameter > {
  static const char* value()
  {
    return "f3c5433e44d0019f0b3eade90114da07";
  }

  static const char* value(const ::vrep_common::simRosSetIntegerParameter&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetIntegerParameter > {
  static const char* value()
  {
    return "vrep_common/simRosSetIntegerParameter";
  }

  static const char* value(const ::vrep_common::simRosSetIntegerParameter&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetIntegerParameterRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetIntegerParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosSetIntegerParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosSetIntegerParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetIntegerParameterRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetIntegerParameter > 
template<>
struct DataType< ::vrep_common::simRosSetIntegerParameterRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosSetIntegerParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetIntegerParameterResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetIntegerParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosSetIntegerParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosSetIntegerParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetIntegerParameterResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetIntegerParameter > 
template<>
struct DataType< ::vrep_common::simRosSetIntegerParameterResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosSetIntegerParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETINTEGERPARAMETER_H
