// Generated by gencpp from file vrep_common/simRosLoadModel.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSLOADMODEL_H
#define VREP_COMMON_MESSAGE_SIMROSLOADMODEL_H

#include <ros/service_traits.h>


#include <vrep_common/simRosLoadModelRequest.h>
#include <vrep_common/simRosLoadModelResponse.h>


namespace vrep_common
{

struct simRosLoadModel
{

typedef simRosLoadModelRequest Request;
typedef simRosLoadModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosLoadModel
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosLoadModel > {
  static const char* value()
  {
    return "e90a06de566d298ef7f6c1c63b525a29";
  }

  static const char* value(const ::vrep_common::simRosLoadModel&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosLoadModel > {
  static const char* value()
  {
    return "vrep_common/simRosLoadModel";
  }

  static const char* value(const ::vrep_common::simRosLoadModel&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosLoadModelRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosLoadModel > 
template<>
struct MD5Sum< ::vrep_common::simRosLoadModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosLoadModel >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosLoadModelRequest> should match 
// service_traits::DataType< ::vrep_common::simRosLoadModel > 
template<>
struct DataType< ::vrep_common::simRosLoadModelRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosLoadModel >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosLoadModelResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosLoadModel > 
template<>
struct MD5Sum< ::vrep_common::simRosLoadModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosLoadModel >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosLoadModelResponse> should match 
// service_traits::DataType< ::vrep_common::simRosLoadModel > 
template<>
struct DataType< ::vrep_common::simRosLoadModelResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosLoadModel >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSLOADMODEL_H
