// Generated by gencpp from file vrep_common/simRosStopSimulation.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSTOPSIMULATION_H
#define VREP_COMMON_MESSAGE_SIMROSSTOPSIMULATION_H

#include <ros/service_traits.h>


#include <vrep_common/simRosStopSimulationRequest.h>
#include <vrep_common/simRosStopSimulationResponse.h>


namespace vrep_common
{

struct simRosStopSimulation
{

typedef simRosStopSimulationRequest Request;
typedef simRosStopSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosStopSimulation
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosStopSimulation > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::vrep_common::simRosStopSimulation&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosStopSimulation > {
  static const char* value()
  {
    return "vrep_common/simRosStopSimulation";
  }

  static const char* value(const ::vrep_common::simRosStopSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosStopSimulationRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosStopSimulation > 
template<>
struct MD5Sum< ::vrep_common::simRosStopSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosStopSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosStopSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosStopSimulationRequest> should match 
// service_traits::DataType< ::vrep_common::simRosStopSimulation > 
template<>
struct DataType< ::vrep_common::simRosStopSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosStopSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosStopSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosStopSimulationResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosStopSimulation > 
template<>
struct MD5Sum< ::vrep_common::simRosStopSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosStopSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosStopSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosStopSimulationResponse> should match 
// service_traits::DataType< ::vrep_common::simRosStopSimulation > 
template<>
struct DataType< ::vrep_common::simRosStopSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosStopSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosStopSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSTOPSIMULATION_H
