// Generated by gencpp from file vrep_common/simRosGetCollisionHandle.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLE_H
#define VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetCollisionHandleRequest.h>
#include <vrep_common/simRosGetCollisionHandleResponse.h>


namespace vrep_common
{

struct simRosGetCollisionHandle
{

typedef simRosGetCollisionHandleRequest Request;
typedef simRosGetCollisionHandleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetCollisionHandle
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandle > {
  static const char* value()
  {
    return "c921683644719c386866fcd63b2e041d";
  }

  static const char* value(const ::vrep_common::simRosGetCollisionHandle&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetCollisionHandle > {
  static const char* value()
  {
    return "vrep_common/simRosGetCollisionHandle";
  }

  static const char* value(const ::vrep_common::simRosGetCollisionHandle&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetCollisionHandleRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetCollisionHandle > 
template<>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetCollisionHandle >::value();
  }
  static const char* value(const ::vrep_common::simRosGetCollisionHandleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetCollisionHandleRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetCollisionHandle > 
template<>
struct DataType< ::vrep_common::simRosGetCollisionHandleRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetCollisionHandle >::value();
  }
  static const char* value(const ::vrep_common::simRosGetCollisionHandleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetCollisionHandleResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetCollisionHandle > 
template<>
struct MD5Sum< ::vrep_common::simRosGetCollisionHandleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetCollisionHandle >::value();
  }
  static const char* value(const ::vrep_common::simRosGetCollisionHandleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetCollisionHandleResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetCollisionHandle > 
template<>
struct DataType< ::vrep_common::simRosGetCollisionHandleResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetCollisionHandle >::value();
  }
  static const char* value(const ::vrep_common::simRosGetCollisionHandleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETCOLLISIONHANDLE_H
