// Generated by gencpp from file vrep_common/simRosGetDialogResult.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETDIALOGRESULT_H
#define VREP_COMMON_MESSAGE_SIMROSGETDIALOGRESULT_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetDialogResultRequest.h>
#include <vrep_common/simRosGetDialogResultResponse.h>


namespace vrep_common
{

struct simRosGetDialogResult
{

typedef simRosGetDialogResultRequest Request;
typedef simRosGetDialogResultResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetDialogResult
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetDialogResult > {
  static const char* value()
  {
    return "3a2c67a393403ca4628ae721d28678fb";
  }

  static const char* value(const ::vrep_common::simRosGetDialogResult&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetDialogResult > {
  static const char* value()
  {
    return "vrep_common/simRosGetDialogResult";
  }

  static const char* value(const ::vrep_common::simRosGetDialogResult&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetDialogResultRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetDialogResult > 
template<>
struct MD5Sum< ::vrep_common::simRosGetDialogResultRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetDialogResult >::value();
  }
  static const char* value(const ::vrep_common::simRosGetDialogResultRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetDialogResultRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetDialogResult > 
template<>
struct DataType< ::vrep_common::simRosGetDialogResultRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetDialogResult >::value();
  }
  static const char* value(const ::vrep_common::simRosGetDialogResultRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetDialogResultResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetDialogResult > 
template<>
struct MD5Sum< ::vrep_common::simRosGetDialogResultResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetDialogResult >::value();
  }
  static const char* value(const ::vrep_common::simRosGetDialogResultResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetDialogResultResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetDialogResult > 
template<>
struct DataType< ::vrep_common::simRosGetDialogResultResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetDialogResult >::value();
  }
  static const char* value(const ::vrep_common::simRosGetDialogResultResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETDIALOGRESULT_H
