// Generated by gencpp from file vrep_common/simRosGetVisionSensorDepthBuffer.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORDEPTHBUFFER_H
#define VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORDEPTHBUFFER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetVisionSensorDepthBufferRequest.h>
#include <vrep_common/simRosGetVisionSensorDepthBufferResponse.h>


namespace vrep_common
{

struct simRosGetVisionSensorDepthBuffer
{

typedef simRosGetVisionSensorDepthBufferRequest Request;
typedef simRosGetVisionSensorDepthBufferResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetVisionSensorDepthBuffer
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBuffer > {
  static const char* value()
  {
    return "4ba1b459e0a6f0de6bdb7a5376ec08af";
  }

  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBuffer&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetVisionSensorDepthBuffer > {
  static const char* value()
  {
    return "vrep_common/simRosGetVisionSensorDepthBuffer";
  }

  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBuffer&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBufferRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBuffer > 
template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBufferRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBuffer >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBufferRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetVisionSensorDepthBufferRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetVisionSensorDepthBuffer > 
template<>
struct DataType< ::vrep_common::simRosGetVisionSensorDepthBufferRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetVisionSensorDepthBuffer >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBufferRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBufferResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBuffer > 
template<>
struct MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBufferResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetVisionSensorDepthBuffer >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBufferResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetVisionSensorDepthBufferResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetVisionSensorDepthBuffer > 
template<>
struct DataType< ::vrep_common::simRosGetVisionSensorDepthBufferResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetVisionSensorDepthBuffer >::value();
  }
  static const char* value(const ::vrep_common::simRosGetVisionSensorDepthBufferResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETVISIONSENSORDEPTHBUFFER_H
