// Generated by gencpp from file vrep_common/simRosGetJointState.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETJOINTSTATE_H
#define VREP_COMMON_MESSAGE_SIMROSGETJOINTSTATE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetJointStateRequest.h>
#include <vrep_common/simRosGetJointStateResponse.h>


namespace vrep_common
{

struct simRosGetJointState
{

typedef simRosGetJointStateRequest Request;
typedef simRosGetJointStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetJointState
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetJointState > {
  static const char* value()
  {
    return "e3e87944e85555d62f7a59817ea5aee6";
  }

  static const char* value(const ::vrep_common::simRosGetJointState&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetJointState > {
  static const char* value()
  {
    return "vrep_common/simRosGetJointState";
  }

  static const char* value(const ::vrep_common::simRosGetJointState&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetJointStateRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetJointState > 
template<>
struct MD5Sum< ::vrep_common::simRosGetJointStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetJointState >::value();
  }
  static const char* value(const ::vrep_common::simRosGetJointStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetJointStateRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetJointState > 
template<>
struct DataType< ::vrep_common::simRosGetJointStateRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetJointState >::value();
  }
  static const char* value(const ::vrep_common::simRosGetJointStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetJointStateResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetJointState > 
template<>
struct MD5Sum< ::vrep_common::simRosGetJointStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetJointState >::value();
  }
  static const char* value(const ::vrep_common::simRosGetJointStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetJointStateResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetJointState > 
template<>
struct DataType< ::vrep_common::simRosGetJointStateResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetJointState >::value();
  }
  static const char* value(const ::vrep_common::simRosGetJointStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETJOINTSTATE_H
