// Generated by gencpp from file vrep_common/simRosSetVisionSensorImage.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETVISIONSENSORIMAGE_H
#define VREP_COMMON_MESSAGE_SIMROSSETVISIONSENSORIMAGE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetVisionSensorImageRequest.h>
#include <vrep_common/simRosSetVisionSensorImageResponse.h>


namespace vrep_common
{

struct simRosSetVisionSensorImage
{

typedef simRosSetVisionSensorImageRequest Request;
typedef simRosSetVisionSensorImageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetVisionSensorImage
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetVisionSensorImage > {
  static const char* value()
  {
    return "e312c990380d2289b9e07f7a0295ef34";
  }

  static const char* value(const ::vrep_common::simRosSetVisionSensorImage&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetVisionSensorImage > {
  static const char* value()
  {
    return "vrep_common/simRosSetVisionSensorImage";
  }

  static const char* value(const ::vrep_common::simRosSetVisionSensorImage&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetVisionSensorImageRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetVisionSensorImage > 
template<>
struct MD5Sum< ::vrep_common::simRosSetVisionSensorImageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosSetVisionSensorImageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetVisionSensorImageRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetVisionSensorImage > 
template<>
struct DataType< ::vrep_common::simRosSetVisionSensorImageRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosSetVisionSensorImageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetVisionSensorImageResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetVisionSensorImage > 
template<>
struct MD5Sum< ::vrep_common::simRosSetVisionSensorImageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosSetVisionSensorImageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetVisionSensorImageResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetVisionSensorImage > 
template<>
struct DataType< ::vrep_common::simRosSetVisionSensorImageResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetVisionSensorImage >::value();
  }
  static const char* value(const ::vrep_common::simRosSetVisionSensorImageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETVISIONSENSORIMAGE_H
