// Generated by gencpp from file vrep_common/simRosTransferFile.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSTRANSFERFILE_H
#define VREP_COMMON_MESSAGE_SIMROSTRANSFERFILE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosTransferFileRequest.h>
#include <vrep_common/simRosTransferFileResponse.h>


namespace vrep_common
{

struct simRosTransferFile
{

typedef simRosTransferFileRequest Request;
typedef simRosTransferFileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosTransferFile
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosTransferFile > {
  static const char* value()
  {
    return "3c956e5a32cec1f93100fec7ced2ccd4";
  }

  static const char* value(const ::vrep_common::simRosTransferFile&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosTransferFile > {
  static const char* value()
  {
    return "vrep_common/simRosTransferFile";
  }

  static const char* value(const ::vrep_common::simRosTransferFile&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosTransferFileRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosTransferFile > 
template<>
struct MD5Sum< ::vrep_common::simRosTransferFileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosTransferFile >::value();
  }
  static const char* value(const ::vrep_common::simRosTransferFileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosTransferFileRequest> should match 
// service_traits::DataType< ::vrep_common::simRosTransferFile > 
template<>
struct DataType< ::vrep_common::simRosTransferFileRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosTransferFile >::value();
  }
  static const char* value(const ::vrep_common::simRosTransferFileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosTransferFileResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosTransferFile > 
template<>
struct MD5Sum< ::vrep_common::simRosTransferFileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosTransferFile >::value();
  }
  static const char* value(const ::vrep_common::simRosTransferFileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosTransferFileResponse> should match 
// service_traits::DataType< ::vrep_common::simRosTransferFile > 
template<>
struct DataType< ::vrep_common::simRosTransferFileResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosTransferFile >::value();
  }
  static const char* value(const ::vrep_common::simRosTransferFileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSTRANSFERFILE_H
