// Generated by gencpp from file vrep_common/simRosGetArrayParameter.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETARRAYPARAMETER_H
#define VREP_COMMON_MESSAGE_SIMROSGETARRAYPARAMETER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetArrayParameterRequest.h>
#include <vrep_common/simRosGetArrayParameterResponse.h>


namespace vrep_common
{

struct simRosGetArrayParameter
{

typedef simRosGetArrayParameterRequest Request;
typedef simRosGetArrayParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetArrayParameter
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetArrayParameter > {
  static const char* value()
  {
    return "eb14c535a1358defa0617c252d433144";
  }

  static const char* value(const ::vrep_common::simRosGetArrayParameter&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetArrayParameter > {
  static const char* value()
  {
    return "vrep_common/simRosGetArrayParameter";
  }

  static const char* value(const ::vrep_common::simRosGetArrayParameter&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetArrayParameterRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetArrayParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosGetArrayParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetArrayParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetArrayParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetArrayParameterRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetArrayParameter > 
template<>
struct DataType< ::vrep_common::simRosGetArrayParameterRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetArrayParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetArrayParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetArrayParameterResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetArrayParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosGetArrayParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetArrayParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetArrayParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetArrayParameterResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetArrayParameter > 
template<>
struct DataType< ::vrep_common::simRosGetArrayParameterResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetArrayParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetArrayParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETARRAYPARAMETER_H
