// Generated by gencpp from file vrep_common/simRosSetUIButtonLabelRequest.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETUIBUTTONLABELREQUEST_H
#define VREP_COMMON_MESSAGE_SIMROSSETUIBUTTONLABELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vrep_common
{
template <class ContainerAllocator>
struct simRosSetUIButtonLabelRequest_
{
  typedef simRosSetUIButtonLabelRequest_<ContainerAllocator> Type;

  simRosSetUIButtonLabelRequest_()
    : uiHandle(0)
    , buttonID(0)
    , upStateLabel()
    , downStateLabel()  {
    }
  simRosSetUIButtonLabelRequest_(const ContainerAllocator& _alloc)
    : uiHandle(0)
    , buttonID(0)
    , upStateLabel(_alloc)
    , downStateLabel(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _uiHandle_type;
  _uiHandle_type uiHandle;

   typedef int32_t _buttonID_type;
  _buttonID_type buttonID;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _upStateLabel_type;
  _upStateLabel_type upStateLabel;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _downStateLabel_type;
  _downStateLabel_type downStateLabel;





  typedef boost::shared_ptr< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simRosSetUIButtonLabelRequest_

typedef ::vrep_common::simRosSetUIButtonLabelRequest_<std::allocator<void> > simRosSetUIButtonLabelRequest;

typedef boost::shared_ptr< ::vrep_common::simRosSetUIButtonLabelRequest > simRosSetUIButtonLabelRequestPtr;
typedef boost::shared_ptr< ::vrep_common::simRosSetUIButtonLabelRequest const> simRosSetUIButtonLabelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vrep_common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vrep_common': ['/home/alpsark/ros-ws/src/vrep_stack/vrep_common/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e1ad0cb5a7e9bfb5b83bdbdf550ecc4";
  }

  static const char* value(const ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e1ad0cb5a7e9bfbULL;
  static const uint64_t static_value2 = 0x5b83bdbdf550ecc4ULL;
};

template<class ContainerAllocator>
struct DataType< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vrep_common/simRosSetUIButtonLabelRequest";
  }

  static const char* value(const ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
int32 uiHandle\n\
int32 buttonID\n\
string upStateLabel\n\
string downStateLabel\n\
";
  }

  static const char* value(const ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uiHandle);
      stream.next(m.buttonID);
      stream.next(m.upStateLabel);
      stream.next(m.downStateLabel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simRosSetUIButtonLabelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vrep_common::simRosSetUIButtonLabelRequest_<ContainerAllocator>& v)
  {
    s << indent << "uiHandle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.uiHandle);
    s << indent << "buttonID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buttonID);
    s << indent << "upStateLabel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.upStateLabel);
    s << indent << "downStateLabel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.downStateLabel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETUIBUTTONLABELREQUEST_H
