// Generated by gencpp from file vrep_common/simRosClearStringSignal.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSCLEARSTRINGSIGNAL_H
#define VREP_COMMON_MESSAGE_SIMROSCLEARSTRINGSIGNAL_H

#include <ros/service_traits.h>


#include <vrep_common/simRosClearStringSignalRequest.h>
#include <vrep_common/simRosClearStringSignalResponse.h>


namespace vrep_common
{

struct simRosClearStringSignal
{

typedef simRosClearStringSignalRequest Request;
typedef simRosClearStringSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosClearStringSignal
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosClearStringSignal > {
  static const char* value()
  {
    return "78c7f457aa3ca9421b43a9c08cf8400a";
  }

  static const char* value(const ::vrep_common::simRosClearStringSignal&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosClearStringSignal > {
  static const char* value()
  {
    return "vrep_common/simRosClearStringSignal";
  }

  static const char* value(const ::vrep_common::simRosClearStringSignal&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosClearStringSignalRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosClearStringSignal > 
template<>
struct MD5Sum< ::vrep_common::simRosClearStringSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosClearStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosClearStringSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosClearStringSignalRequest> should match 
// service_traits::DataType< ::vrep_common::simRosClearStringSignal > 
template<>
struct DataType< ::vrep_common::simRosClearStringSignalRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosClearStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosClearStringSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosClearStringSignalResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosClearStringSignal > 
template<>
struct MD5Sum< ::vrep_common::simRosClearStringSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosClearStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosClearStringSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosClearStringSignalResponse> should match 
// service_traits::DataType< ::vrep_common::simRosClearStringSignal > 
template<>
struct DataType< ::vrep_common::simRosClearStringSignalResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosClearStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosClearStringSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSCLEARSTRINGSIGNAL_H
