// Generated by gencpp from file vrep_common/simRosSetSphericalJointMatrix.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETSPHERICALJOINTMATRIX_H
#define VREP_COMMON_MESSAGE_SIMROSSETSPHERICALJOINTMATRIX_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetSphericalJointMatrixRequest.h>
#include <vrep_common/simRosSetSphericalJointMatrixResponse.h>


namespace vrep_common
{

struct simRosSetSphericalJointMatrix
{

typedef simRosSetSphericalJointMatrixRequest Request;
typedef simRosSetSphericalJointMatrixResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetSphericalJointMatrix
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetSphericalJointMatrix > {
  static const char* value()
  {
    return "ff6022ac5ed35d4a73c1ed756bc036db";
  }

  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrix&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetSphericalJointMatrix > {
  static const char* value()
  {
    return "vrep_common/simRosSetSphericalJointMatrix";
  }

  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrix&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetSphericalJointMatrixRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetSphericalJointMatrix > 
template<>
struct MD5Sum< ::vrep_common::simRosSetSphericalJointMatrixRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetSphericalJointMatrix >::value();
  }
  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrixRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetSphericalJointMatrixRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetSphericalJointMatrix > 
template<>
struct DataType< ::vrep_common::simRosSetSphericalJointMatrixRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetSphericalJointMatrix >::value();
  }
  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrixRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetSphericalJointMatrixResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetSphericalJointMatrix > 
template<>
struct MD5Sum< ::vrep_common::simRosSetSphericalJointMatrixResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetSphericalJointMatrix >::value();
  }
  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrixResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetSphericalJointMatrixResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetSphericalJointMatrix > 
template<>
struct DataType< ::vrep_common::simRosSetSphericalJointMatrixResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetSphericalJointMatrix >::value();
  }
  static const char* value(const ::vrep_common::simRosSetSphericalJointMatrixResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETSPHERICALJOINTMATRIX_H
