// Generated by gencpp from file vrep_common/simRosLoadUI.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSLOADUI_H
#define VREP_COMMON_MESSAGE_SIMROSLOADUI_H

#include <ros/service_traits.h>


#include <vrep_common/simRosLoadUIRequest.h>
#include <vrep_common/simRosLoadUIResponse.h>


namespace vrep_common
{

struct simRosLoadUI
{

typedef simRosLoadUIRequest Request;
typedef simRosLoadUIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosLoadUI
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosLoadUI > {
  static const char* value()
  {
    return "16005ff8dad636c8c963ce5d5ee0c3c1";
  }

  static const char* value(const ::vrep_common::simRosLoadUI&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosLoadUI > {
  static const char* value()
  {
    return "vrep_common/simRosLoadUI";
  }

  static const char* value(const ::vrep_common::simRosLoadUI&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosLoadUIRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosLoadUI > 
template<>
struct MD5Sum< ::vrep_common::simRosLoadUIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosLoadUI >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadUIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosLoadUIRequest> should match 
// service_traits::DataType< ::vrep_common::simRosLoadUI > 
template<>
struct DataType< ::vrep_common::simRosLoadUIRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosLoadUI >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadUIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosLoadUIResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosLoadUI > 
template<>
struct MD5Sum< ::vrep_common::simRosLoadUIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosLoadUI >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadUIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosLoadUIResponse> should match 
// service_traits::DataType< ::vrep_common::simRosLoadUI > 
template<>
struct DataType< ::vrep_common::simRosLoadUIResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosLoadUI >::value();
  }
  static const char* value(const ::vrep_common::simRosLoadUIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSLOADUI_H
