// Generated by gencpp from file vrep_common/simRosCallScriptFunction.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSCALLSCRIPTFUNCTION_H
#define VREP_COMMON_MESSAGE_SIMROSCALLSCRIPTFUNCTION_H

#include <ros/service_traits.h>


#include <vrep_common/simRosCallScriptFunctionRequest.h>
#include <vrep_common/simRosCallScriptFunctionResponse.h>


namespace vrep_common
{

struct simRosCallScriptFunction
{

typedef simRosCallScriptFunctionRequest Request;
typedef simRosCallScriptFunctionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosCallScriptFunction
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosCallScriptFunction > {
  static const char* value()
  {
    return "df820c7b6bf8dac295ae340e203b4857";
  }

  static const char* value(const ::vrep_common::simRosCallScriptFunction&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosCallScriptFunction > {
  static const char* value()
  {
    return "vrep_common/simRosCallScriptFunction";
  }

  static const char* value(const ::vrep_common::simRosCallScriptFunction&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosCallScriptFunctionRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosCallScriptFunction > 
template<>
struct MD5Sum< ::vrep_common::simRosCallScriptFunctionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosCallScriptFunction >::value();
  }
  static const char* value(const ::vrep_common::simRosCallScriptFunctionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosCallScriptFunctionRequest> should match 
// service_traits::DataType< ::vrep_common::simRosCallScriptFunction > 
template<>
struct DataType< ::vrep_common::simRosCallScriptFunctionRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosCallScriptFunction >::value();
  }
  static const char* value(const ::vrep_common::simRosCallScriptFunctionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosCallScriptFunctionResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosCallScriptFunction > 
template<>
struct MD5Sum< ::vrep_common::simRosCallScriptFunctionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosCallScriptFunction >::value();
  }
  static const char* value(const ::vrep_common::simRosCallScriptFunctionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosCallScriptFunctionResponse> should match 
// service_traits::DataType< ::vrep_common::simRosCallScriptFunction > 
template<>
struct DataType< ::vrep_common::simRosCallScriptFunctionResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosCallScriptFunction >::value();
  }
  static const char* value(const ::vrep_common::simRosCallScriptFunctionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSCALLSCRIPTFUNCTION_H
