// Generated by gencpp from file vrep_common/simRosGetIntegerParameter.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETINTEGERPARAMETER_H
#define VREP_COMMON_MESSAGE_SIMROSGETINTEGERPARAMETER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetIntegerParameterRequest.h>
#include <vrep_common/simRosGetIntegerParameterResponse.h>


namespace vrep_common
{

struct simRosGetIntegerParameter
{

typedef simRosGetIntegerParameterRequest Request;
typedef simRosGetIntegerParameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetIntegerParameter
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetIntegerParameter > {
  static const char* value()
  {
    return "60ddbc43aea06d61ad0817005dac2c22";
  }

  static const char* value(const ::vrep_common::simRosGetIntegerParameter&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetIntegerParameter > {
  static const char* value()
  {
    return "vrep_common/simRosGetIntegerParameter";
  }

  static const char* value(const ::vrep_common::simRosGetIntegerParameter&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetIntegerParameterRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetIntegerParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosGetIntegerParameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetIntegerParameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetIntegerParameterRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetIntegerParameter > 
template<>
struct DataType< ::vrep_common::simRosGetIntegerParameterRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetIntegerParameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetIntegerParameterResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetIntegerParameter > 
template<>
struct MD5Sum< ::vrep_common::simRosGetIntegerParameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetIntegerParameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetIntegerParameterResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetIntegerParameter > 
template<>
struct DataType< ::vrep_common::simRosGetIntegerParameterResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetIntegerParameter >::value();
  }
  static const char* value(const ::vrep_common::simRosGetIntegerParameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETINTEGERPARAMETER_H
