// Generated by gencpp from file vrep_common/simRosSetModelProperty.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETMODELPROPERTY_H
#define VREP_COMMON_MESSAGE_SIMROSSETMODELPROPERTY_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetModelPropertyRequest.h>
#include <vrep_common/simRosSetModelPropertyResponse.h>


namespace vrep_common
{

struct simRosSetModelProperty
{

typedef simRosSetModelPropertyRequest Request;
typedef simRosSetModelPropertyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetModelProperty
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetModelProperty > {
  static const char* value()
  {
    return "7f97a83fe47ddd7d7a57ba9fe6623621";
  }

  static const char* value(const ::vrep_common::simRosSetModelProperty&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetModelProperty > {
  static const char* value()
  {
    return "vrep_common/simRosSetModelProperty";
  }

  static const char* value(const ::vrep_common::simRosSetModelProperty&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetModelPropertyRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetModelProperty > 
template<>
struct MD5Sum< ::vrep_common::simRosSetModelPropertyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetModelProperty >::value();
  }
  static const char* value(const ::vrep_common::simRosSetModelPropertyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetModelPropertyRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetModelProperty > 
template<>
struct DataType< ::vrep_common::simRosSetModelPropertyRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetModelProperty >::value();
  }
  static const char* value(const ::vrep_common::simRosSetModelPropertyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetModelPropertyResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetModelProperty > 
template<>
struct MD5Sum< ::vrep_common::simRosSetModelPropertyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetModelProperty >::value();
  }
  static const char* value(const ::vrep_common::simRosSetModelPropertyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetModelPropertyResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetModelProperty > 
template<>
struct DataType< ::vrep_common::simRosSetModelPropertyResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetModelProperty >::value();
  }
  static const char* value(const ::vrep_common::simRosSetModelPropertyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETMODELPROPERTY_H
