// Generated by gencpp from file vrep_common/simRosGetUISlider.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSGETUISLIDER_H
#define VREP_COMMON_MESSAGE_SIMROSGETUISLIDER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosGetUISliderRequest.h>
#include <vrep_common/simRosGetUISliderResponse.h>


namespace vrep_common
{

struct simRosGetUISlider
{

typedef simRosGetUISliderRequest Request;
typedef simRosGetUISliderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosGetUISlider
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosGetUISlider > {
  static const char* value()
  {
    return "5406790310ec56ad5fb998c1037f3650";
  }

  static const char* value(const ::vrep_common::simRosGetUISlider&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosGetUISlider > {
  static const char* value()
  {
    return "vrep_common/simRosGetUISlider";
  }

  static const char* value(const ::vrep_common::simRosGetUISlider&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosGetUISliderRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetUISlider > 
template<>
struct MD5Sum< ::vrep_common::simRosGetUISliderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosGetUISliderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetUISliderRequest> should match 
// service_traits::DataType< ::vrep_common::simRosGetUISlider > 
template<>
struct DataType< ::vrep_common::simRosGetUISliderRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosGetUISliderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosGetUISliderResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosGetUISlider > 
template<>
struct MD5Sum< ::vrep_common::simRosGetUISliderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosGetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosGetUISliderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosGetUISliderResponse> should match 
// service_traits::DataType< ::vrep_common::simRosGetUISlider > 
template<>
struct DataType< ::vrep_common::simRosGetUISliderResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosGetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosGetUISliderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSGETUISLIDER_H
