// Generated by gencpp from file vrep_common/simRosRemoveUI.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSREMOVEUI_H
#define VREP_COMMON_MESSAGE_SIMROSREMOVEUI_H

#include <ros/service_traits.h>


#include <vrep_common/simRosRemoveUIRequest.h>
#include <vrep_common/simRosRemoveUIResponse.h>


namespace vrep_common
{

struct simRosRemoveUI
{

typedef simRosRemoveUIRequest Request;
typedef simRosRemoveUIResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosRemoveUI
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosRemoveUI > {
  static const char* value()
  {
    return "6833353cd429b83819dab869600ce745";
  }

  static const char* value(const ::vrep_common::simRosRemoveUI&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosRemoveUI > {
  static const char* value()
  {
    return "vrep_common/simRosRemoveUI";
  }

  static const char* value(const ::vrep_common::simRosRemoveUI&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosRemoveUIRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosRemoveUI > 
template<>
struct MD5Sum< ::vrep_common::simRosRemoveUIRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosRemoveUI >::value();
  }
  static const char* value(const ::vrep_common::simRosRemoveUIRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosRemoveUIRequest> should match 
// service_traits::DataType< ::vrep_common::simRosRemoveUI > 
template<>
struct DataType< ::vrep_common::simRosRemoveUIRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosRemoveUI >::value();
  }
  static const char* value(const ::vrep_common::simRosRemoveUIRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosRemoveUIResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosRemoveUI > 
template<>
struct MD5Sum< ::vrep_common::simRosRemoveUIResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosRemoveUI >::value();
  }
  static const char* value(const ::vrep_common::simRosRemoveUIResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosRemoveUIResponse> should match 
// service_traits::DataType< ::vrep_common::simRosRemoveUI > 
template<>
struct DataType< ::vrep_common::simRosRemoveUIResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosRemoveUI >::value();
  }
  static const char* value(const ::vrep_common::simRosRemoveUIResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSREMOVEUI_H
