// Generated by gencpp from file vrep_common/simRosReadDistance.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSREADDISTANCE_H
#define VREP_COMMON_MESSAGE_SIMROSREADDISTANCE_H

#include <ros/service_traits.h>


#include <vrep_common/simRosReadDistanceRequest.h>
#include <vrep_common/simRosReadDistanceResponse.h>


namespace vrep_common
{

struct simRosReadDistance
{

typedef simRosReadDistanceRequest Request;
typedef simRosReadDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosReadDistance
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosReadDistance > {
  static const char* value()
  {
    return "099258cb82ad99c080c59f94344f9f24";
  }

  static const char* value(const ::vrep_common::simRosReadDistance&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosReadDistance > {
  static const char* value()
  {
    return "vrep_common/simRosReadDistance";
  }

  static const char* value(const ::vrep_common::simRosReadDistance&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosReadDistanceRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosReadDistance > 
template<>
struct MD5Sum< ::vrep_common::simRosReadDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosReadDistance >::value();
  }
  static const char* value(const ::vrep_common::simRosReadDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosReadDistanceRequest> should match 
// service_traits::DataType< ::vrep_common::simRosReadDistance > 
template<>
struct DataType< ::vrep_common::simRosReadDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosReadDistance >::value();
  }
  static const char* value(const ::vrep_common::simRosReadDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosReadDistanceResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosReadDistance > 
template<>
struct MD5Sum< ::vrep_common::simRosReadDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosReadDistance >::value();
  }
  static const char* value(const ::vrep_common::simRosReadDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosReadDistanceResponse> should match 
// service_traits::DataType< ::vrep_common::simRosReadDistance > 
template<>
struct DataType< ::vrep_common::simRosReadDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosReadDistance >::value();
  }
  static const char* value(const ::vrep_common::simRosReadDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSREADDISTANCE_H
