// Generated by gencpp from file vrep_common/simRosSetUISlider.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETUISLIDER_H
#define VREP_COMMON_MESSAGE_SIMROSSETUISLIDER_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetUISliderRequest.h>
#include <vrep_common/simRosSetUISliderResponse.h>


namespace vrep_common
{

struct simRosSetUISlider
{

typedef simRosSetUISliderRequest Request;
typedef simRosSetUISliderResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetUISlider
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetUISlider > {
  static const char* value()
  {
    return "a3a4f1222511591c647246b4904a9a10";
  }

  static const char* value(const ::vrep_common::simRosSetUISlider&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetUISlider > {
  static const char* value()
  {
    return "vrep_common/simRosSetUISlider";
  }

  static const char* value(const ::vrep_common::simRosSetUISlider&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetUISliderRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetUISlider > 
template<>
struct MD5Sum< ::vrep_common::simRosSetUISliderRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosSetUISliderRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetUISliderRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetUISlider > 
template<>
struct DataType< ::vrep_common::simRosSetUISliderRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosSetUISliderRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetUISliderResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetUISlider > 
template<>
struct MD5Sum< ::vrep_common::simRosSetUISliderResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosSetUISliderResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetUISliderResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetUISlider > 
template<>
struct DataType< ::vrep_common::simRosSetUISliderResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetUISlider >::value();
  }
  static const char* value(const ::vrep_common::simRosSetUISliderResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETUISLIDER_H
