// Generated by gencpp from file vrep_common/simRosSetObjectPosition.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETOBJECTPOSITION_H
#define VREP_COMMON_MESSAGE_SIMROSSETOBJECTPOSITION_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetObjectPositionRequest.h>
#include <vrep_common/simRosSetObjectPositionResponse.h>


namespace vrep_common
{

struct simRosSetObjectPosition
{

typedef simRosSetObjectPositionRequest Request;
typedef simRosSetObjectPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetObjectPosition
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetObjectPosition > {
  static const char* value()
  {
    return "6f49de0c0a94265fc772061f892cd142";
  }

  static const char* value(const ::vrep_common::simRosSetObjectPosition&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetObjectPosition > {
  static const char* value()
  {
    return "vrep_common/simRosSetObjectPosition";
  }

  static const char* value(const ::vrep_common::simRosSetObjectPosition&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetObjectPositionRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetObjectPosition > 
template<>
struct MD5Sum< ::vrep_common::simRosSetObjectPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::vrep_common::simRosSetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetObjectPositionRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetObjectPosition > 
template<>
struct DataType< ::vrep_common::simRosSetObjectPositionRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::vrep_common::simRosSetObjectPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetObjectPositionResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetObjectPosition > 
template<>
struct MD5Sum< ::vrep_common::simRosSetObjectPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::vrep_common::simRosSetObjectPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetObjectPositionResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetObjectPosition > 
template<>
struct DataType< ::vrep_common::simRosSetObjectPositionResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetObjectPosition >::value();
  }
  static const char* value(const ::vrep_common::simRosSetObjectPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETOBJECTPOSITION_H
