// Generated by gencpp from file vrep_common/simRosSetStringSignal.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSSETSTRINGSIGNAL_H
#define VREP_COMMON_MESSAGE_SIMROSSETSTRINGSIGNAL_H

#include <ros/service_traits.h>


#include <vrep_common/simRosSetStringSignalRequest.h>
#include <vrep_common/simRosSetStringSignalResponse.h>


namespace vrep_common
{

struct simRosSetStringSignal
{

typedef simRosSetStringSignalRequest Request;
typedef simRosSetStringSignalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosSetStringSignal
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosSetStringSignal > {
  static const char* value()
  {
    return "c49759e205be8f8195cc764a3a6b6c4d";
  }

  static const char* value(const ::vrep_common::simRosSetStringSignal&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosSetStringSignal > {
  static const char* value()
  {
    return "vrep_common/simRosSetStringSignal";
  }

  static const char* value(const ::vrep_common::simRosSetStringSignal&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosSetStringSignalRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetStringSignal > 
template<>
struct MD5Sum< ::vrep_common::simRosSetStringSignalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosSetStringSignalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetStringSignalRequest> should match 
// service_traits::DataType< ::vrep_common::simRosSetStringSignal > 
template<>
struct DataType< ::vrep_common::simRosSetStringSignalRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosSetStringSignalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosSetStringSignalResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosSetStringSignal > 
template<>
struct MD5Sum< ::vrep_common::simRosSetStringSignalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosSetStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosSetStringSignalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosSetStringSignalResponse> should match 
// service_traits::DataType< ::vrep_common::simRosSetStringSignal > 
template<>
struct DataType< ::vrep_common::simRosSetStringSignalResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosSetStringSignal >::value();
  }
  static const char* value(const ::vrep_common::simRosSetStringSignalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSSETSTRINGSIGNAL_H
