// Generated by gencpp from file vrep_common/simRosPauseSimulation.msg
// DO NOT EDIT!


#ifndef VREP_COMMON_MESSAGE_SIMROSPAUSESIMULATION_H
#define VREP_COMMON_MESSAGE_SIMROSPAUSESIMULATION_H

#include <ros/service_traits.h>


#include <vrep_common/simRosPauseSimulationRequest.h>
#include <vrep_common/simRosPauseSimulationResponse.h>


namespace vrep_common
{

struct simRosPauseSimulation
{

typedef simRosPauseSimulationRequest Request;
typedef simRosPauseSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simRosPauseSimulation
} // namespace vrep_common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vrep_common::simRosPauseSimulation > {
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::vrep_common::simRosPauseSimulation&) { return value(); }
};

template<>
struct DataType< ::vrep_common::simRosPauseSimulation > {
  static const char* value()
  {
    return "vrep_common/simRosPauseSimulation";
  }

  static const char* value(const ::vrep_common::simRosPauseSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::vrep_common::simRosPauseSimulationRequest> should match 
// service_traits::MD5Sum< ::vrep_common::simRosPauseSimulation > 
template<>
struct MD5Sum< ::vrep_common::simRosPauseSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosPauseSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosPauseSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosPauseSimulationRequest> should match 
// service_traits::DataType< ::vrep_common::simRosPauseSimulation > 
template<>
struct DataType< ::vrep_common::simRosPauseSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosPauseSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosPauseSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vrep_common::simRosPauseSimulationResponse> should match 
// service_traits::MD5Sum< ::vrep_common::simRosPauseSimulation > 
template<>
struct MD5Sum< ::vrep_common::simRosPauseSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vrep_common::simRosPauseSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosPauseSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vrep_common::simRosPauseSimulationResponse> should match 
// service_traits::DataType< ::vrep_common::simRosPauseSimulation > 
template<>
struct DataType< ::vrep_common::simRosPauseSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::vrep_common::simRosPauseSimulation >::value();
  }
  static const char* value(const ::vrep_common::simRosPauseSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VREP_COMMON_MESSAGE_SIMROSPAUSESIMULATION_H
